[project]
name = "jquants-api-client"
version = "0.0.1"
authors = [
    { name = "J-Quants Project Contributors", email = "j-quants@jpx.co.jp" },
]
description = "J-Quants API Client Library"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
keywords = ["jquants", "api", "client", "J-Quants"]

[project.urls]
"Homepage" = "https://github.com/J-Quants/jquants-api-client-python"
"Bug Tracker" = "https://github.com/J-Quants/jquants-api-client-python/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.4.3"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
mypy = "^0.971"
pyproject-flake8 = "^0.0.1-alpha.4"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 120
max-complexity = 18
ignore = "E203,E266,W503,"
